export const coinTypes = [
  {label: 'AE29', value: 'This is an AE29 coin, which means it’s 29mm in diameter and made of bronze.  Its denomination is unknown.'},
  {label: 'As', value: 'The as, also known as an assarius, was a coin first introduced during the Roman Republic and continued to be used during the Roman Empire.  Asses were initially made of bronze, but later issues of these coins were made of copper.  Ten asses were equivalent to one denarius.'},
  {label: 'Centenionalis', value: 'The centenionalis (plural centenionales) is a large bronze coin.  Centenionales were minted under Constantius II and his brother Constans as an attempt to reintroduce bigger bronze coins to the Roman Empire’s currency.  However, these centenionales were not fated to last.  By 395, just 34 years after Constantius’ rule, only small bronze coins were minted by the empire.'},
  {label: 'Denarius', value: 'The denarius (plural denarii) was the Roman Empire’s benchmark silver coin for over 400 years (c. 211 BC - c. 244 AD).'},
  {label: 'Double Denarius', value: 'The double denarius, sometimes called an antoninianus or aurelianianus, was a result of inflation in the Roman Empire.  In 215 AD, Caracalla stopped production of the regular silver denarius and introduced the double denarius, which only used 1.5x the material of a regular denarius.  In 274 AD under Aurelian, the composition of double denarii changed from a silver alloy to bronze with a silver coating.  Some consider double denarii from 274 and beyond to be a different denomination (aurelianiani) than previous double denarii (antoniniani).  On a double denarius’s obverse, emperors are depicted wearing a radiate crown and empresses are pictured with a crescent moon under their shoulders.'},
  {label: 'Dupondius', value: 'The dupondius was a brass coin used in the Roman Republic and Roman Empire.  Dupondius means “two-pounder” in Latin, but even at its introduction the coin weighed less than two Roman pounds.  One dupondius was equivalent to two copper asses, and five dupondii were equivalent to one denarius.'},
  {label: 'Nummus', value: 'Nummus is a Latin word derived from the Greek noummos which has several meanings, one of which is coin.  Nummus can refer to various coins minted during the Roman Republic and Roman Empire. A reduced nummus is a nummus made with less material as the original nummus, resulting in a smaller coin.'},
  {label: 'Sestertius', value: 'Sestertius means “two and a half” in Latin, in reference to its value being worth two and a half asses.  By extension, four sestertii were equivalent to one denarius.  In the Roman Republic, the sestertius was a small silver coin.  In the Roman Empire, it was a large brass coin.'},
  {label: 'Tetradrachm', value: 'The tetradrachm was a large silver coin, named because it was equivalent to four drachmae.  Originally from ancient Greece, this type of coin was adopted by other nations and states including the Roman Empire and Egypt.  The large surface area allowed rulers and governments to convey political messages and advertise themselves.'},
  // {label: 'placeholder', value: 'blah'},
];