export const grades = [
  {label: 'PR', value: 'Poor'},
  {label: 'FA', value: 'Fair'},
  {label: 'AG', value: 'About Good'},
  {label: 'G', value: 'Good'},
  {label: 'VG', value: 'Very Good'},
  {label: 'F', value: 'Fine'},
  {label: 'Ch F', value: 'Choice Fine'},
  {label: 'VF', value: 'Very Fine'},
  {label: 'Ch VF', value: 'Choice Very Fine'},
  {label: 'XF', value: 'Extremely Fine'},
  {label: 'Ch XF', value: 'Choice Extremely Fine'},
  {label: 'AU', value: 'About Uncirculated'},
  {label: 'Ch AU', value: 'Choice About Uncirculated'},
  {label: 'MS', value: 'Mint State'},
  {label: 'Ch MS', value: 'Choice Mint State'},
  {label: 'Gem MS', value: 'Gem Mint State'},
  // {label: 'placeholder', value: 'blah'},
];